- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
   
    - name: Start Tomcat container
      docker_container:
        name: my_app_container
        image: tomcat:latest
        state: started
        ports:
          - "8888:8080"
        detach: yes
        tty: yes
        volumes:
          - /var/lib/jenkins/workspace/ansible_playbook_project_test/target/demo.war:/usr/local/tomcat/webapps/demo.war
