---
- hosts: localhost
#  connection: local
  tasks:
          #    - name: "Debug: List contents of the directory"
          #      shell: ls -l /var/lib/jenkins/workspace/ansible_playbook_project_test/

    - name: copy .war file to docker context folder
      copy:
        src: /var/lib/jenkins/workspace/ansible_playbook_project_test/target/demo.war
        dest: /home/labsuser/.docker/context

    - name: copy jenkinsDocker file to docker context folder
      copy:
        src: /var/lib/jenkins/workspace/ansible_playbook_project_test/target/jenkinsDockerfile
        dest: /home/labsuser/.docker/context

    - name: Build Docker image
      docker_image:
        name: my_auto_image
        path: ~/.docker/build/context/

    - name: "Start docker container"
      docker_container:
        name: my_auto_deployed_app
        image: my_auto_image
        state: started
        #        recreate: yes
        restart: yes
