---
- hosts: webservers
  connection: local
  gather_facts: false
  #  become: true
  tasks:
    - name: Change the working directory provided to build docker image using Jenkins Dockerfile
      shell: docker build -t my_auto_image -f jenkinsDockerfile .
      args:
        chdir: /var/lib/jenkins/workspace/ansible_playbook_project_test/

    - name: start a container
      docker_container:
      name: hello_world_war_demo
      image: my_auto_image
      state: started
      restart: true




