---
- hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: Change the working directory to create demo.war using the pom.xml
      shell: chmod 777 /var/lib/jenkins/workspace/ansible_playbook_project_test/
      args:
        chdir: /var/lib/jenkins/workspace/ansible_playbook_project_test/

    - name: Change the working directory to create demo.war using the pom.xml
      shell: mvn clean package
      args:
        chdir: /var/lib/jenkins/workspace/ansible_playbook_project_test/

    - name: "Debug: List contents of the directory"
      shell: ls -l /var/lib/jenkins/workspace/ansible_playbook_project_test/
