---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
    - name: Change the working directory to create demo.war using mvn clean package
      shell: mvn clean package
      args:
        chdir: /var/lib/jenkins/workspace/ansible_playbook_project_test/

    - name: Start Tomcat container
      docker_container:
        name: my_app_container
        image: tomcat:latest
        state: started
        ports:
          - "8888:8080"
        detach: yes
        tty: yes

    - name: Fetch .war file from local machine
      fetch:
        src: /home/labsuser/helloworld_webapp/target/demo.war
        dest: /tmp/demo.war
        flat: yes

    - name: Copy .war file to Tomcat webapps directory
      copy:
        src: /tmp/demo.war
        dest: /usr/local/tomcat/webapps/demo.war
        #    - name: Create Tomcat webapps directory if it doesn't exist
        #      file:
        #        path: /usr/local/tomcat/webapps
        #        state: directory
        #      become: yes
        
        #    - name: Copy .war file to Docker context folder
        #      copy:
        #        src: /var/lib/jenkins/workspace/ansible_playbook_project_test/target/demo.war
        #        dest: /usr/local/tomcat/webapps/demo.war
