---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Change the working directory to create demo.war using the pom.xml
      shell: mvn clean package
      args:
        chdir: /var/lib/jenkins/workspace/ansible_playbook_project_test/

    - name: Build Docker image using tomcat repo
      docker_image:
        name: my_auto_image
        dockerfile: /var/lib/jenkins/workspace/ansible_playbook_project_test/target/jenkinsDockerfile

    - name: Copy .war file to Docker context folder
      copy:
        src: /var/lib/jenkins/workspace/ansible_playbook_project_test/target/demo.war
        dest: /usr/local/tomcat/webapps/demo.war
